version: "3"
services:
  back_app_icm:
    depends_on:
      - postgresdb-server
    restart: always
    build: .
    ports:
      - "7070:3000"
    volumes:
      - .:/usr/src/app
  postgresdb-server:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: icmdb
      POSTGRES_DB: icmdb
volumes:
  postgres-data: